### ISSUE TITLE
Login, CSS

### ISSUE THREAD

**Issue by ragdassi** [hack4impact-calpoly/go-see-foundation#1]
**Description**
Create Frontend **styling** for Login component in `authentication` folder in the file `login.css`. Work collaboratively with  teammate working on login component

**Acceptance Criteria**

- [x] Make it look like Figma Design
- [x] Write 'classes' for different parts of page
- [x] Media Query/tag to make the site device-responsive (mobile and desktop). 2 good places to reference: https://zellwk.com/blog/how-to-write-mobile-first-css/
https://www.w3schools.com/css/css_rwd_mediaqueries.asp
- [x] Collaborated (Zoom and/or Slack) with Software Developer working on login component

**Additional Information**
Link to Figma: https://www.figma.com/file/01WIn8JpMzWWLahrP6army/Untitled?type=design&node-id=0-1&mode=design&t=Vb37CBAkUedCMa4v-0

** Contact Britta, Ryan or Eduardo with your email if you are unable to access the Figma. 

<img width="423" alt="Screen Shot 2024-01-19 at 6 10 31 PM" src="https://github.com/hack4impact-calpoly/go-see-foundation/assets/113940065/8f94a856-39fe-4027-98cc-fdb3f4bc19ce">

**Comment by BrightTNut** [comment]
is it completed

**Comment by seanmnguyen** [comment]
Not yet. I'm still working on the media query/tags since I'm not too familiar with that at the moment

**Comment by BrightTNut** [comment]
i like to work on it
