### ISSUE TITLE
AWS research

### ISSUE THREAD

**Issue by eduardo661** [hack4impact-calpoly/go-see-foundation#21]
**Description**
In order to save images of each event, we're going to store images in a s3 bucket. This was all be possible through the use of AWS. AWS was not covered in boot camp so before we implement a bucket into our project, we need to do some research on how to get this done. 

**Acceptance Criteria**
Basic research into how to save images to an s3 bucket and retrieving images. More emphasis on the form that data takes in between and whats happening.

Steps:
- Read
- Read some more

**Additional Information**
https://docs.aws.amazon.com/lookout-for-vision/latest/developer-guide/create-dataset-s3.html

**Comment by idavoong** [comment]
Link to research doc:
https://docs.google.com/document/d/1MPL3Na0UqgBDmkwYalActN7qEg7PXpxnJpQiLpIcnFw/edit
