### ISSUE TITLE
Navigation through Screenreader

### ISSUE THREAD

**Issue by eduardo661** [hack4impact-calpoly/go-see-foundation#35]
**Description**
Depending on your computer, you are going to try to use a screen reader on our current website. Note, our website does not feature much if any screen reader support so this will mostly be experience / a learning experience. Depending on your computer, use voiceOver for macOS or JAWS for windows. Note, you will be responsible for figuring out how to setup and use the screen reader! If you have any additional questions, let me know!

**Comment by anvch** [comment]
I used NVDA because it is a free option. Here are some notes on my experience with it.
https://docs.google.com/document/d/1d773980xqS_cYfaGJeZaoEYXSJWm3W6xgU1nDzvjHRY/edit?usp=sharing

**Comment by eduardo661** [comment]
Good informative document, nice job!
